artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  bucket_name: chicken-data-2025
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
